#generated from slack. sorry if I forgot to add you. Please PR.
MEMBERS = [
    "Schaus, Pierre",
    "Nijssen, Siegfried",
    "Derval, Guillaume",
    "Deville, Yves",
    "Thomas, Charles",
    "Aglin, Frederic Don-de-dieu",
    "Latour, Anna",
    "Verhaeghe, Hélène",
    "Bouldjedri, Oussama",
    "Mattenet, Alexandre",
    "Pham, Hoang Son",
    "Hamer, Victor",
    "Cuenca Pauta, Erick",
    "Aubry, François",
    "Saint-Guillain, Michael",
    "Ha, Quang Minh",
    "Kameugne, Roger",
    "Branders, Vincent",
    "Gillard, Xavier",
    "Aoga, John",
    "Dupont, Pierre",
    "Gerniers, Alexander"
]